#!/usr/bin/env python3
#-----------------------------------------------------------------------------
#
# TSDuck - The MPEG Transport Stream Toolkit
# Copyright (c) 2026, Jason Chua
# BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
#
#-----------------------------------------------------------------------------
# Independent UDP capture and wire validation for the original FEC transmitter.
# No external implementation code is copied or linked into this BSD test harness.

import argparse
from contextlib import ExitStack
import importlib.util
from pathlib import Path
import select
import socket
import struct
import subprocess
import sys
import tempfile
import time

# Reuse only port reservation and fixture loading from the companion input test.
# The transmitter's parity is checked below without the production encoder/decoder.
spec = importlib.util.spec_from_file_location("fec_input_fixture", Path(__file__).with_name("test-210.py"))
fixture = importlib.util.module_from_spec(spec)
sys.dont_write_bytecode = True
spec.loader.exec_module(fixture)


def collect(process, sockets):
    """Drain every stream while the child runs and for a quiet interval afterward."""
    # Keep original UDP payloads; no RTP parsing is performed until collection finishes.
    # The three sockets can become ready in a different order from send order.
    records = []
    # A monotonic deadline bounds both a stalled pipeline and a missed end of stream.
    # Wall-clock changes cannot make this test hang.
    deadline = time.monotonic() + 20
    quiet = None
    while time.monotonic() < deadline:
        # Drain every stream together so a row or column receive queue cannot overflow.
        # The source is regulated rather than emitted as one machine-dependent burst.
        readable, _, _ = select.select(sockets, [], [], 0.05)
        # Per-stream FIFO order is sufficient; UDP gives no ordering across ports.
        for sock in readable:
            data, source = sock.recvfrom(65536)
            records.append((sockets.index(sock), data, source))
        if process.poll() is not None and not readable:
            # Process exit can precede the final datagram's delivery to our socket.
            quiet = quiet or time.monotonic()
            if time.monotonic() - quiet > 0.2:
                break
        else:
            quiet = None
    else:
        raise RuntimeError("IP output capture timed out")
    # stderr is intentionally small: per-packet debug output could block the child.
    # Exit status is checked before accepting any otherwise valid captured packets.
    error = process.communicate(timeout=2)[1].decode(errors="replace")
    if process.returncode:
        raise RuntimeError(f"IP output exited {process.returncode}: {error}")
    return records


def capture(tsp, source, path, mode, columns, rows, burst, rs204=False, equals=False, matrix_options=True):
    """Capture media and both standard FEC destinations from the real output plugin."""
    # Reserve an even media port and both parity ports atomically before child startup.
    # Failed neighboring binds are retried by the shared fixture utility.
    port, sockets = fixture.listeners()
    # Guard sockets before constructing commands or launching a fallible process.
    # A partially initialized capture must not leak bound ports into the next case.
    with ExitStack() as resources:
        for sock in sockets:
            resources.callback(sock.close)
        # Reserve a distinct local source port so all three streams can be checked.
        local = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        resources.callback(local.close)
        # Use a numeric IPv4 loopback address, independent of localhost DNS preferences.
        # The reserved destination ports cannot be selected as this source port.
        local.bind(("127.0.0.1", 0))
        source_port = local.getsockname()[1]
        local.close()
        # Write deterministic transport bytes without the external fixture's RTP headers.
        # All media timestamps and parity in this capture are generated by TSDuck.
        path.write_bytes(source)
        # Enforce full bursts except the final flush, making datagram counts portable.
        # TTL, TOS, interface and a fixed source port must survive parity transmission.
        command = [tsp, "--bitrate", "2000000", "-I", "file", str(path), "-P", "regulate",
                   "-O", "ip", f"127.0.0.1:{port}", "--enforce-burst", "--packet-burst", str(burst),
                   "--local-address", "127.0.0.1", "--local-port", str(source_port), "--ttl", "8", "--tos", "16"]
        # Fixed media identifiers make sequence wrapping observable without normalizing bytes.
        # The raw case verifies that FEC additions do not introduce encapsulation.
        if mode not in ("raw", "raw-none"):
            command += ["--rtp", "--start-sequence-number", "65520", "--ssrc-identifier", "270544960"]
        if mode not in ("raw", "rtp"):
            # Required values accept both spellings through the shared Args parser.
            # Explicit none must preserve either raw UDP or RTP without producing parity.
            value = "none" if mode == "raw-none" else mode
            command += [f"--smpte-2022-fec={value}"] if equals else ["--smpte-2022-fec", value]
            if mode != "raw-none" and mode != "none" and matrix_options:
                command += ["--smpte-2022-l", str(columns), "--smpte-2022-d", str(rows)]
        # Input is TS188; existing output behavior appends the default all-FF RS trailer.
        # The parity layer must protect those transmitted bytes unchanged.
        if rs204:
            command += ["--rs204"]
        # Keep process lifetime nested inside socket lifetime, including capture failure.
        # stdout is unused; stderr explains configuration or socket failures.
        process = subprocess.Popen(command, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
        try:
            records = collect(process, sockets)
        finally:
            # Reap the process before releasing the guarded socket group on failure.
            if process.poll() is None:
                process.kill()
                process.communicate()
        # ST 2022-1 requires a shared source port, not three independently chosen sockets.
        # Checking every datagram detects accidental source changes on either FEC stream.
        if not records or any(sender != ("127.0.0.1", source_port) for _, _, sender in records):
            raise RuntimeError("Media and parity must use the same requested source IP/port")
        return records


def media_payload(data, rs204):
    """Check the TS operating point and return its 188-byte transport content."""
    # Validate lengths before visiting packet boundaries or slicing a trailer.
    # Short final bursts are valid, while partial transport packets are not.
    size = 204 if rs204 else 188
    if not data or len(data) % size or len(data) > 7 * size:
        raise RuntimeError("Invalid TS media length")
    # Compare transport content independently of whether the wire carries RS204 trailers.
    # This also proves that enabling FEC leaves TS payloads unchanged.
    result = bytearray()
    for offset in range(0, len(data), size):
        if data[offset] != 0x47:
            raise RuntimeError("Invalid TS synchronization")
        if rs204 and data[offset + 188:offset + 204] != b"\xff" * 16:
            raise RuntimeError("RS204 output changed the default trailer")
        result.extend(data[offset:offset + 188])
    return bytes(result)


def xor_group(group):
    """Compute independent recovery fields directly from captured original wire data."""
    # Original media, not production parity helpers, determine every expected bit.
    # FEC storage uses the longest payload, even when XOR length recovery is zero.
    # A shorter member contributes implicit zero bytes beyond its actual end.
    longest = max(len(packet) - 12 for packet in group)
    payload = bytearray(longest)
    # Header recovery uses original media PT and timestamps, not the FEC RTP clock.
    # These reductions are independent of production encoder code.
    length = payload_type = timestamp = 0
    for packet in group:
        length ^= len(packet) - 12
        payload_type ^= packet[1]
        timestamp ^= struct.unpack_from("!I", packet, 4)[0]
        for offset, value in enumerate(packet[12:]):
            payload[offset] ^= value
    return length, payload_type, timestamp, bytes(payload)


def expected_columns(media_count, columns, rows, block_aligned):
    """Count only complete equations with an actual subsequent emission interval."""
    # Aligned columns are interleaved at c*D in the next block, as in Annex C.
    # Staggered groups recur once per matrix, with the initial phase explicitly in SNBase.
    phases = [col * rows if block_aligned else (col % rows) * columns + col for col in range(columns)]
    # Neither arrangement may flush delayed parity by synthesizing extra media.
    return sum(block * columns * rows + phase < media_count
               for block in range(1, 1 + media_count // (columns * rows)) for phase in phases)


def check_parity(records, media, mode, columns, rows):
    """Associate each captured equation with its media and check all protected bytes."""
    sequences = [struct.unpack_from("!H", packet, 2)[0] for packet in media]
    # Cases span a single 16-bit wrap, so each wire sequence identifies exactly one packet.
    # Member selection uses explicit SNBase/Offset/NA rather than assumed block alignment.
    positions = {sequence: index for index, sequence in enumerate(sequences)}
    # Row and column RTP sequence numbers have separate counters.
    # Their total counts are checked against the normative schedule afterward.
    counts = [0, 0]
    for role, packet, _ in records:
        if role == 0:
            continue
        # Header size is checked before reading any recovery field or member index.
        if len(packet) <= 28 or packet[:2] != b"\x80\x60" or packet[8:12] != b"\0" * 4:
            raise RuntimeError("Invalid FEC RTP profile")
        row = role == 2
        stride, count = (1, columns) if row else (columns, rows)
        base = struct.unpack_from("!H", packet, 12)[0]
        # Both geometry and the reserved header bits are checked independently.
        if packet[17:20] != b"\0" * 3 or packet[24:28] != bytes((0x40 if row else 0, stride, count, 0)):
            raise RuntimeError("Invalid extended FEC header")
        try:
            indices = [positions[(base + index * stride) % 65536] for index in range(count)]
        except KeyError as error:
            raise RuntimeError("Parity protects absent media") from error
        # Dimensionality does not imply alignment: inspect actual protected membership.
        # This prevents an aligned encoder from passing the staggered mode cases.
        first = indices[0]
        phase = first % columns if mode.endswith("-b") else (first % columns % rows) * columns + first % columns
        if (row and first % columns != 0) or (not row and first % (columns * rows) != phase):
            raise RuntimeError("Incorrect row membership or column alignment")
        length, payload_type, timestamp, payload = xor_group([media[index] for index in indices])
        if packet[14:17] != struct.pack("!HB", length, 0x80 | payload_type) or \
           packet[20:24] != struct.pack("!I", timestamp) or packet[28:] != payload:
            raise RuntimeError("Incorrect recovery fields or XOR payload")
        # Global arrival order across UDP ports is irrelevant to independent stream numbering.
        # A shared sequence counter would create gaps here and fail this check.
        counter = counts[role - 1]
        if struct.unpack_from("!H", packet, 2)[0] != counter % 65536:
            raise RuntimeError("Parity streams must have independent consecutive RTP sequences")
        counts[role - 1] += 1
    # Count delayed equations independently of global arrival order across UDP sockets.
    # Explicit none and omitted FEC must never generate either parity stream.
    columns_count = expected_columns(len(media), columns, rows, mode.endswith("-b")) if mode.startswith(("1d", "2d")) else 0
    rows_count = len(media) // columns if mode.startswith("2d") else 0
    if counts != [columns_count, rows_count]:
        raise RuntimeError(f"Unexpected parity counts {counts}, expected {[columns_count, rows_count]}")
    return counts


def verify(records, source, mode, columns, rows, rs204):
    """Check original media preservation before using it as the parity oracle."""
    media = [data for role, data, _ in records if role == 0]
    # Each stream is read in its own FIFO order, including sequence wrap.
    if mode not in ("raw", "raw-none"):
        for index, packet in enumerate(media):
            if len(packet) <= 12 or packet[:2] != b"\x80\x21" or \
               struct.unpack_from("!H", packet, 2)[0] != (65520 + index) % 65536 or \
               struct.unpack_from("!I", packet, 8)[0] != 270544960:
                raise RuntimeError("Incorrect or non-consecutive media RTP profile")
    # Exact bytes catch omitted, duplicated, reordered or corrupted packets, beyond counts alone.
    # Only after preservation succeeds may captured media serve as the parity oracle.
    restored = b"".join(media_payload(packet if mode in ("raw", "raw-none") else packet[12:], rs204) for packet in media)
    if restored != source:
        raise RuntimeError("IP output changed, omitted, duplicated or reordered original TS bytes")
    counts = check_parity(records, media, mode, columns, rows)
    return media, counts


def invalid_options(tsp):
    """Fail before sending media for every incompatible option combination."""
    # Profile restrictions are checked by the output before its socket starts sending.
    # Match the relevant validation message rather than accepting any unrelated failure.
    cases = [(["--smpte-2022-fec"], None),
             (["--smpte-2022-fec", "2d"], "requires --rtp"),
             (["--smpte-2022-d", "4"], "require enabled"),
             (["--smpte-2022-l", "4"], "require enabled"),
             (["--smpte-2022-fec", "none", "--smpte-2022-l", "4"], "require enabled"),
             (["--rtp", "--smpte-2022-fec", "2d", "--payload-type", "34"], "payload type 33"),
             (["--rtp", "--smpte-2022-fec", "2d", "--packet-burst", "8"], "at most 7"),
             (["--rtp", "--smpte-2022-fec", "2d", "--smpte-2022-l", "3"], "at least 4 columns"),
             (["--rtp", "--smpte-2022-fec", "2d-b", "--smpte-2022-l", "20", "--smpte-2022-d", "20"], "at most 100"),
             (["--fec=2"], None)]
    # M1/M2 select vendor sub-packet timing, not additional standardized wire modes.
    # Unsupported labels must be rejected instead of silently mapped to approximate behavior.
    cases += [(["--rtp", "--smpte-2022-fec", mode], None) for mode in ("2d-m1", "2d-m1-b", "2d-m2", "2d-m2-b")]
    for options, message in cases:
        # The validation target is always the IP output plugin, not the input syntax.
        # The positional null count keeps the source finite on every supported platform.
        command = [tsp, "-I", "null", "1", "-O", "ip", "127.0.0.1:5000"] + options
        # Finite null input bounds an accidentally accepted configuration as well.
        # A timeout is an explicit failure instead of silently abandoning a child.
        result = subprocess.run(command, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, timeout=5)
        # RTPFECOptionsTest captures every parser diagnostic synchronously.
        # CLI exit status remains mandatory; loadArgs validation messages are
        # also required here, since they occur after successful parsing.
        if result.returncode != 1 or (message is not None and message not in result.stderr.decode(errors="replace")):
            raise RuntimeError(f"Incorrect validation for FEC options: {options}, exit={result.returncode}, stderr={result.stderr!r}")
    # Test both odd ports and the two upper even ports that cannot carry N+4.
    # No sockets are reserved for these cases because transmission must never begin.
    for port in (5001, 65532, 65534):
        # Odd media and overflowing two-stream destination ports must be rejected.
        result = subprocess.run([tsp, "-I", "null", "1", "-O", "ip", f"127.0.0.1:{port}", "--rtp", "--smpte-2022-fec", "2d"],
                                stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, timeout=5)
        if result.returncode != 1 or "even media destination port" not in result.stderr.decode(errors="replace"):
            raise RuntimeError("Invalid FEC destination accepted")
    print("PASS invalid-options: incompatible profile, geometry and ports rejected")


def main():
    # The shell harness resolves the development executable for this repository's branch.
    # No installed TSDuck version is silently substituted for the implementation under test.
    parser = argparse.ArgumentParser()
    parser.add_argument("--tsp", required=True)
    args = parser.parse_args()
    records = fixture.load_fixture(Path(__file__).with_name("test-210.rtp"))
    # The fixture contains generated video, not captured third-party program content.
    # Its provenance and regeneration procedure are documented in test-210.md.
    original = b"".join(data[12:] for role, data in records if role == 0)
    # Reuse only the fixture's generated transport content, never its original parity.
    cases = [("raw", "raw", 4, 4, 7, False), ("rtp", "rtp", 4, 4, 7, False),
             ("none-raw", "raw-none", 4, 4, 7, False), ("none-rtp", "none", 4, 4, 7, False),
             ("column-1x4", "1d-b", 1, 4, 1, False), ("column-20x5", "1d-b", 20, 5, 7, False),
             ("column-5x20", "1d-b", 5, 20, 4, False), ("default-4x4", "2d-b", 4, 4, 7, False),
             ("two-dimensional-10x10", "2d-b", 10, 10, 4, False),
             ("rs204-4x4", "2d-b", 4, 4, 7, True), ("short-final-burst", "2d-b", 4, 4, 7, False),
             ("staggered-annex-b", "1d", 4, 5, 7, False), ("staggered-common-factor", "1d", 4, 4, 7, False),
             ("staggered-wide", "1d", 20, 5, 7, False), ("staggered-2d", "2d", 4, 4, 7, False),
             ("staggered-large", "2d", 10, 10, 4, False), ("staggered-rs204", "2d", 4, 4, 7, True),
             ("equal-sign-syntax", "2d-b", 4, 4, 7, False)]
    # Keep child inputs and output artifacts outside the test repository.
    # Normal runs neither regenerate the fixture nor alter reference files.
    with tempfile.TemporaryDirectory(prefix="tsduck-output-fec-") as name:
        directory = Path(name)
        for case, mode, columns, rows, burst, rs204 in cases:
            # Three matrices plus a tail cover multiple groups and non-flushable final columns.
            # Matrix size is in RTP datagrams, independent of the TS burst size.
            count = (3 * columns * rows + 2) * burst
            if case == "short-final-burst":
                count += 2  # The final RTP datagram has a shorter payload, not synthetic padding.
            # Repeat the generated TS when a large geometry needs more media than the fixture.
            # Repeated PCR values are handled by normal RTP output; parity still protects actual timestamps.
            source = (original * (1 + count * 188 // len(original)))[:count * 188]
            capture_records = capture(args.tsp, source, directory / "source.ts", mode, columns, rows, burst, rs204,
                                      equals=case == "equal-sign-syntax", matrix_options=case != "default-4x4")
            media, counts = verify(capture_records, source, mode, columns, rows, rs204)
            # References contain only deterministic summaries, never ports or RTP timestamps.
            # All recovered wire bytes were compared before this summary is emitted.
            print(f"PASS {case}: {len(media)} media, {counts[0]} column, {counts[1]} row datagrams; exact media and parity")
    invalid_options(args.tsp)


if __name__ == "__main__":
    main()
